### ISSUE TITLE
isOpen Method on TransactionalGraph

### ISSUE THREAD

**Issue by wselwood** [tinkerpop/blueprints#518]
If a graph has been commited or rolled back there is no way to tell. 

We have to keep our own state if we have committed the graph so we can deal with automatically rolling back in a finally block.

**Comment by spmallette** [comment]
Such things are resolve in TinkerPop3: 

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#transactions
http://www.tinkerpop.com/javadocs/3.0.0.M6/core/com/tinkerpop/gremlin/structure/Transaction.html#isOpen--

As we have frozen major development on the TinkerPop 2.x line of code, I don't imagine we will make such an interface change here at this point.  Thanks.
