### ISSUE TITLE
OSGi Support

### ISSUE THREAD

**Issue by skahmann** [tinkerpop/blueprints#524]
Would you be open to enabling OSGi support for the project? It's pretty easy to do with the maven-bundle-plugin.

Thanks!

**Comment by spmallette** [comment]
We aren't doing major changes to blueprints given work on TP3.  We are largely in maintenance mode at this point for Blueprints and other 2.x components of TinkerPop.  Note that the issue of OSGi was brought up for TP3 as well:

https://github.com/tinkerpop/tinkerpop3/issues/266

and we don't expect to support it.  I know this is problematic for developers trying to work in that environment, but it is just not something we expect to include.  Sorry about that.
