### ISSUE TITLE
Nested tags in data tag

### ISSUE THREAD

**Issue by mha6992** [tinkerpop/blueprints#526]
Hi there, assuming I have some like this in an edge tag, how can I still read it into a graph?
# <edge id="7" source="2" target="4">
        <data key="bus_name" value="parameters"  />
       <data key="bus_type" value="prameter_list">
               <parameter id="1" name="country">
              	</parameter>
              	<parameter id="2" name="city">
              	</parameter>
       <data/>
       <data key="bus_source_index" value="1" />
       <data key="bus_destination_index" value="1" />
</edge>

**Comment by spmallette** [comment]
it depends on the `Graph` implementation that you use.  If you use Neo4j, for example, it accepts primitive arrays as a property type:

http://neo4j.com/docs/stable/graphdb-neo4j-properties.html
