### ISSUE TITLE
Update to Neo4j 2.2.1

### ISSUE THREAD

**Issue by niclashoyer** [tinkerpop/blueprints#529]
The `blueprints-neo4j2-graph` package is based on Neo4j `2.1.6`, but the most recent version is `2.2.1`.

**Comment by spmallette** [comment]
have you tried to bump the version yourself?  do you happen to know if the tests pass?

**Comment by mikesname** [comment]
It does not compile with the version bumped since they have changed the API a bit. The first problem I noticed involved checking if elements are in a write transaction. Will put in a PR if I manage to resolve this myself.

**Comment by joeyfreund** [comment]
Seems like this is resolved. Can we close this issue?

**Comment by niclashoyer** [comment]
@spmallette is the new snapshot with compatibility for 2.1.1 available somewhere? Sonatype Snapshots?

**Comment by spmallette** [comment]
yes - deployed to sonatype snapshots.
