### ISSUE TITLE
Consistent iteration order + arbitrary starting vertex

### ISSUE THREAD

**Issue by devinrsmith** [tinkerpop/blueprints#530]
1. Does the blueprint api guarantee that I'll get the same whole graph vertex iteration order from call to call? (If not directly implied, I'm assuming it is the case that some implementations do guarantee this.)
2. If so, is there a way to jump into that same whole graph vertex iteration order from an arbitrary starting vertex? (Looking at `com.tinkerpop.blueprints.Graph` it doesn't seem possible...)

I could impose my own ordering on the graph with a linked list, but that's more work than I would like if the api can provide that functionality.

**Comment by spmallette** [comment]
There are no tests in the Blueprints test suite to enforce order.  It is entirely up to the underlying graph database to decide the order in which elements are returned.  I'm not aware of any implementations that do enforce a specific order, but I suppose it is possible.  

Lack of order enforcement is also true in TinkerPop3 and I wouldn't expect that to change.  I think you will have to come up with your own approach.
