### ISSUE TITLE
Blueprints 2.6.0 Test fail

### ISSUE THREAD

**Issue by CasperWW** [tinkerpop/blueprints#532]
I downloaded the 2.6.0 release from Github and I tried to build it with:
       
       mvn -e -X clean install
It fails the build with:

	Results :

	Failed tests:   testNormal(com.tinkerpop.blueprints.util.io.gml.GMLWriterTest): expected:<...	blueprintsId "3"(..)
	  testUseIds(com.tinkerpop.blueprints.util.io.gml.GMLWriterTest): expected:<...	](..)
	  testNormal(com.tinkerpop.blueprints.impls.tg.TinkerMetadataWriterTest): expected:<5> but was:<6>

	Tests in error: 
	  testGraphSONWriterTestSuite(com.tinkerpop.blueprints.impls.tg.TinkerGraphTest)

	Tests run: 256, Failures: 3, Errors: 1, Skipped: 0

**Comment by spmallette** [comment]
Strange.  You say you "downloaded 2.6.0 from GitHub" but i'm not sure if that means you downloaded the tag distribution that GitHub provides via the the "releases" link or if you cloned the repo from that 2.6.0 tag.  I can't certify what GitHub does in their tarball distribution - i'd think it is just an archive of the tag so I'm not sure why it doesn't work.  I will say that cloning the repo, checking out the tag and building works fine.  We released off that tag so I'm not sure how there could be anything amiss there.

**Comment by CasperWW** [comment]
Hi Stephen thanks for your reply. Excuse me for not specifying all details. I dowloaded blueprints from [releases](https://github.com/tinkerpop/blueprints/releases/tag/2.6.0) and I tried your approach:

     git clone https://github.com/tinkerpop/blueprints.git
     cd blueprints
     git checkout -b tmp 2.6.0
     mvn -e -X clean install

It fails with the same errors as noted in my initial post. Note I'm on OS X 10.10 with Java JDK 1.8.0_31.
Any suggestions ?

**Comment by spmallette** [comment]
uh - might not compile on java 8.  stick to java 7 - i did :)

**Comment by CasperWW** [comment]
Confirmed: does not compile on Java 8. Java 7 is max version. Thanks for your help.
