### ISSUE TITLE
set multiple edges on one vertex

### ISSUE THREAD

**Issue by Safouane** [tinkerpop/blueprints#536]
can i set multiple edges on one vertex whereas every edge represent a specific direction with a specific weight?

**Comment by spmallette** [comment]
yes - a vertex can have multiple edges.  they must be directional edges and they can have an arbitrary set of properties (key/value pairs) - which would allow you to set a "weight".  

in the future, please use the mailing list for these kinds of questions: https://groups.google.com/forum/#!forum/gremlin-users
